import { JSONSchemaType } from 'ajv';
import { DiskInterface } from '../../app/models/disk/disk.interface';
import { protocolMetaSchema } from './protocol-meta.schema';
import { gitlabConfigSchema } from './gitlab-config.schema';
import { ProtocolServer, ResultsMode } from '../../app/utilities/constants';
import { uploadSummarySchema } from './upload-summary.schema';
import { mediaReposSchema } from './media-repos.schema';
import { savedDevicesSchema } from './saved-devices.schema';
import { nullable } from '../../app/utilities/safe-parsing';

export const diskSchema: JSONSchemaType<DiskInterface> = {
  type: 'object',
  properties: {
    activeProtocolMeta: nullable(protocolMetaSchema),
    adminSkipMode: { type: 'boolean', default: false },
    appDeveloperMode: { type: 'boolean', default: false },
    appDeveloperModeCount: { type: 'integer', default: 0 },
    audhere: { type: 'string', default: '' },
    autoUpload: { type: 'boolean', default: true },
    availableProtocolsMeta: {
      type: 'object',
      additionalProperties: protocolMetaSchema,
      properties: {
        // Commenting out purdue shakedown while we develop
        // PurdueShakedown: {
        //      date: new Date().toJSON(),
        //      version: '0.0',
        //      server: ProtocolServer.Developer,
        //      admin: true,
        //     creator: "Creare",
        //     name: "Purdue Shakedown",
        //     path: "protocols/purdue-shakedown"
        // },
        develop: protocolMetaSchema,
      },
      default: {
        develop: {
          date: new Date().toJSON(),
          version: '0.0',
          server: ProtocolServer.Developer,
          admin: true,
          creator: 'Creare',
          name: 'develop',
          path: 'protocols/develop',
        },
      },
      required: ['develop'],
    },
    cha: {
      type: 'object',
      properties: {
        bluetoothType: { type: 'string', default: '' },
        embeddedFirmwareBuildDate: { type: 'string', default: '' },
        embeddedFirmwareTag: { type: 'string', default: '' },
        myCha: { type: 'string', default: '' },
      },
      default: { bluetoothType: '', embeddedFirmwareBuildDate: '', embeddedFirmwareTag: '', myCha: '' },
      required: ['bluetoothType', 'embeddedFirmwareBuildDate', 'embeddedFirmwareTag', 'myCha'],
    },
    contentURI: { type: 'string', default: null },
    debugMode: { type: 'boolean', default: false },
    disableAudioStreaming: nullable({ type: 'boolean', default: true }),
    disableLogs: { type: 'boolean', default: false },
    disableVolume: nullable({ type: 'boolean' }),
    downloadInProgress: { type: 'boolean', default: false },
    externalMode: { type: 'boolean', default: false },
    extStorageRootDir: nullable({ type: 'string' }),
    extStorageUuidDir: nullable({ type: 'string' }),
    gitlab: {
      type: 'object',
      properties: {
        repos: { type: 'array', items: { type: 'string' }, default: [] },
        useSeperateResultsRepo: { type: 'boolean', default: false },
        useTagsOnly: { type: 'boolean', default: true },
      },
      default: { repos: [], useSeperateResultsRepo: false, useTagsOnly: true },
      required: ['repos', 'useSeperateResultsRepo', 'useTagsOnly'],
    },
    gitlabConfig: {
      ...gitlabConfigSchema,
      default: {
        repository: gitlabConfigSchema.properties.repository.default,
        tag: gitlabConfigSchema.properties.tag.default,
        host: gitlabConfigSchema.properties.host.default,
        token: gitlabConfigSchema.properties.token.default,
        group: gitlabConfigSchema.properties.group.default,
      },
    },
    headset: { type: 'string', default: 'None' },
    interApp: {
      type: 'object',
      properties: {
        appName: { type: 'string', default: '' },
        dataIn: { type: 'string', default: '' },
        dataOut: { type: 'string', default: '' },
      },
      default: { appName: '', dataIn: '', dataOut: '' },
      required: ['appName', 'dataIn', 'dataOut'],
    },
    language: { type: 'string', default: 'English' },
    lastReleaseCheck: { type: 'string', default: '' },
    mediaRepos: { type: 'array', items: mediaReposSchema, default: [] },
    maxLogRows: { type: 'integer', default: 1000 },
    numLogRows: { type: 'integer', default: 0 },
    pin: { type: 'string', default: '7114' },
    preventExports: { type: 'boolean', default: false },
    preventUploads: { type: 'boolean', default: true },
    qrcodeConfig: nullable({ type: 'object' }),
    recordTestLocation: nullable({ type: 'boolean' }),
    reloadingBrowser: { type: 'boolean', default: false },
    requireEncryptedResults: { type: 'boolean', default: false },
    resultsMode: { type: 'string', enum: Object.values(ResultsMode), default: ResultsMode.ExportOnly },
    server: { type: 'string', enum: Object.values(ProtocolServer), default: ProtocolServer.LocalServer },
    servers: {
      type: 'object',
      properties: {
        gitlab: {
          type: 'object',
          properties: {
            group: nullable({ type: 'string' }),
            host: nullable({ type: 'string' }),
            resultsGroup: nullable({ type: 'string' }),
            resultsRepo: { type: 'string', default: 'results' },
            repository: nullable({ type: 'string' }),
            token: nullable({ type: 'string' }),
            version: nullable({ type: 'string' }),
          },
          default: { resultsRepo: 'results' },
          required: ['resultsRepo'],
        },
        localServer: {
          type: 'object',
          properties: {
            protocolDir: { type: 'string', default: 'tabsint-protocols' },
            resultsDir: { type: 'string', default: 'tabsint-results' },
            resultsDirUri: { type: 'string', default: '' },
          },
          default: { protocolDir: 'tabsint-protocols', resultsDir: 'tabsint-results', resultsDirUri: '' },
          required: ['protocolDir', 'resultsDir', 'resultsDirUri'],
        },
      },
      default: {
        gitlab: { resultsRepo: 'results' },
        localServer: { protocolDir: 'tabsint-protocols', resultsDir: 'tabsint-results', resultsDirUri: '' },
      },
      required: ['gitlab', 'localServer'],
    },
    showUploadSummary: { type: 'boolean', default: true },
    showDisclaimer: { type: 'boolean', default: true },
    suppressAlerts: { type: 'boolean', default: false },
    tabletGain: { type: 'number', default: 12.34 },
    tabletLocation: {
      type: 'object',
      properties: {
        latitude: nullable({ type: 'number' }),
        longitude: nullable({ type: 'number' }),
        accuracy: nullable({ type: 'number' }),
      },
      default: {},
      required: [],
    },
    uploadSummary: { type: 'array', items: uploadSummarySchema, default: [] },
    validateProtocols: { type: 'boolean', default: true },
    versionCheck: { type: 'boolean', default: false },
    savedDevices: {
      ...savedDevicesSchema,
      default: {
        tympan: savedDevicesSchema.properties.tympan.default,
        cha: savedDevicesSchema.properties.cha.default,
        svantek: savedDevicesSchema.properties.svantek.default,
      },
    },
  },
  required: [
    'adminSkipMode',
    'appDeveloperMode',
    'appDeveloperModeCount',
    'audhere',
    'autoUpload',
    'availableProtocolsMeta',
    'cha',
    'contentURI',
    'debugMode',
    'disableLogs',
    'downloadInProgress',
    'externalMode',
    'gitlab',
    'gitlabConfig',
    'headset',
    'interApp',
    'language',
    'lastReleaseCheck',
    'mediaRepos',
    'maxLogRows',
    'numLogRows',
    'pin',
    'preventExports',
    'preventUploads',
    'reloadingBrowser',
    'requireEncryptedResults',
    'resultsMode',
    'server',
    'servers',
    'showUploadSummary',
    'showDisclaimer',
    'suppressAlerts',
    'tabletGain',
    'tabletLocation',
    'uploadSummary',
    'validateProtocols',
    'versionCheck',
    'savedDevices',
  ],
};
