import { JSONSchemaType } from 'ajv';
import { gitlabConfigSchema } from './gitlab-config.schema';
import { BluetoothType, ProtocolServer, ResultsMode } from '../../app/utilities/constants';
import { nullable } from '../../app/utilities/safe-parsing';
import { Preferences } from '../../app/interfaces/preferences.interface';

export const preferencesSchema: JSONSchemaType<Preferences> = {
  type: 'object',
  properties: {
    adminSkipMode: { type: 'boolean', default: false },
    appDeveloperMode: { type: 'boolean', default: false },
    autoUpload: { type: 'boolean', default: true },
    debugMode: { type: 'boolean', default: false },
    disableAudioStreaming: nullable({ type: 'boolean', default: true }),
    disableLogs: { type: 'boolean', default: false },
    disableVolume: { type: 'boolean', default: false },
    externalMode: { type: 'boolean', default: false },
    gitlab: {
      type: 'object',
      properties: {
        repos: { type: 'array', items: { type: 'string' }, default: [] },
        useSeperateResultsRepo: { type: 'boolean', default: false },
        useTagsOnly: { type: 'boolean', default: true },
      },
      default: { repos: [], useSeperateResultsRepo: false, useTagsOnly: true },
      required: ['repos', 'useSeperateResultsRepo', 'useTagsOnly'],
    },
    gitlabConfig: {
      ...gitlabConfigSchema,
      default: {
        repository: gitlabConfigSchema.properties.repository.default,
        tag: gitlabConfigSchema.properties.tag.default,
        host: gitlabConfigSchema.properties.host.default,
        token: gitlabConfigSchema.properties.token.default,
        group: gitlabConfigSchema.properties.group.default,
      },
    },
    language: { type: 'string', default: 'en' },
    maxLogRows: { type: 'integer', default: 1000 },
    pin: { type: 'string', default: '7114' },
    preventExports: { type: 'boolean', default: false },
    preventUploads: { type: 'boolean', default: true },
    recordTestLocation: nullable({ type: 'boolean' }),
    requireEncryptedResults: { type: 'boolean', default: false },
    resultsMode: { type: 'string', enum: Object.values(ResultsMode), default: ResultsMode.ExportOnly },
    server: { type: 'string', enum: Object.values(ProtocolServer), default: ProtocolServer.LocalServer },
    servers: {
      type: 'object',
      properties: {
        gitlab: {
          type: 'object',
          properties: {
            group: nullable({ type: 'string' }),
            host: nullable({ type: 'string' }),
            resultsGroup: nullable({ type: 'string' }),
            resultsRepo: { type: 'string', default: 'results' },
            repository: nullable({ type: 'string' }),
            token: nullable({ type: 'string' }),
            version: nullable({ type: 'string' }),
          },
          default: { resultsRepo: 'results' },
          required: ['resultsRepo'],
        },
        localServer: {
          type: 'object',
          properties: {
            protocolDir: { type: 'string', default: 'tabsint-protocols' },
            resultsDir: { type: 'string', default: 'tabsint-results' },
            resultsDirUri: { type: 'string', default: '' },
          },
          default: { protocolDir: 'tabsint-protocols', resultsDir: 'tabsint-results', resultsDirUri: '' },
          required: ['protocolDir', 'resultsDir', 'resultsDirUri'],
        },
      },
      default: {
        gitlab: { resultsRepo: 'results' },
        localServer: { protocolDir: 'tabsint-protocols', resultsDir: 'tabsint-results', resultsDirUri: '' },
      },
      required: ['gitlab', 'localServer'],
    },
    showUploadSummary: { type: 'boolean', default: true },
    suppressAlerts: { type: 'boolean', default: false },
    tabletGain: { type: 'number', nullable: true, default: undefined },
    validateProtocols: { type: 'boolean', default: true },
    versionCheck: { type: 'boolean', default: false },
    wahtsConnectionType: { type: 'string', enum: Object.values(BluetoothType), default: BluetoothType.BLUETOOTH_LE },
    ignoreFirmwareUpdates: { type: 'boolean', default: false },
    showTympanPanel: nullable({ type: 'boolean', default: true }),
    showWahtsPanel: nullable({ type: 'boolean', default: false }),
    showDuodosePanel: nullable({ type: 'boolean', default: false }),
    showSvantekPanel: nullable({ type: 'boolean', default: false }),
    enableHeadsetMediaManagement: nullable({ type: 'boolean', default: false }),
  },
  required: [
    'adminSkipMode',
    'appDeveloperMode',
    'autoUpload',
    'debugMode',
    'disableLogs',
    'disableVolume',
    'externalMode',
    'gitlab',
    'gitlabConfig',
    'language',
    'maxLogRows',
    'pin',
    'preventExports',
    'preventUploads',
    'requireEncryptedResults',
    'resultsMode',
    'server',
    'servers',
    'showUploadSummary',
    'suppressAlerts',
    'validateProtocols',
    'versionCheck',
    'wahtsConnectionType',
    'ignoreFirmwareUpdates',
  ],
};
