import { JSONSchemaType } from 'ajv';
import { GapResponseAreaInterface } from '../../app/views/response-area/response-areas/gap/gap.interface';

export const gapSchema: JSONSchemaType<GapResponseAreaInterface> = {
  type: 'object',
  description: 'CHA - Gap Detection Test',
  properties: {
    type: { type: 'string', enum: ['gapResponseArea'] },
    enableSkip: { type: 'boolean', nullable: true, default: false },
    responseRequired: { type: 'boolean', nullable: true, default: false },
    tabsintId: { type: 'string', nullable: true, default: '1' },
    autoSubmit: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: 'Go straight to next page once this page is complete',
    },
    autoBegin: {
      type: 'boolean',
      nullable: true,
      default: true,
      description: "Go straight into exam, without having to press the 'Begin' button",
    },
    feedback: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: 'Shows the user which blocks contain the signal during the presentation',
    },
    feedbackDelay: {
      type: 'number',
      nullable: true,
      default: 1000,
      description: 'Number of milliseconds to show the digits after the presentation before clearing the keypad.',
    },
    training: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: 'Whether or not this represents a training exam.',
    },
    trainingAllowableGapLengths: {
      type: 'array',
      nullable: true,
      default: [40, 20, 12, 6, 0],
      minItems: 5,
      maxItems: 5,
      items: { type: 'number', minimum: 0, maximum: 100 },
      description: 'A 5 item long list of allowable gap lengths, in msec, selectable during training.',
    },
    examInstructions: {
      type: 'string',
      nullable: true,
      description: 'Replaces the top-level instruction text on the CHA exam pages.',
    },
    measureBackground: {
      type: 'string',
      nullable: true,
      enum: ['ThirdOctaveBands'],
      description: 'Select a method to measure background noise after an exam.',
    },
    examProperties: {
      type: 'object',
      nullable: true,
      properties: {
        Channel: { type: 'number', nullable: true, enum: [0, 1, 2], default: 0, description: '0=Left, 1=Right, 2=Both.' },
        TimePres: {
          type: 'number',
          nullable: true,
          default: 4000,
          minimum: 0,
          maximum: 40000,
          description: 'Total length of each noise presentation in msec.',
        },
        LNoise: { type: 'number', nullable: true, default: 65, minimum: 0, maximum: 85, description: 'Presentation level in dBA.' },
        AllowableGapLengths: {
          type: 'array',
          nullable: true,
          default: [70, 60, 50, 45, 40, 35, 30, 25, 20, 16, 13, 10, 7, 4, 2, 1],
          minItems: 1,
          maxItems: 30,
          items: { type: 'number', minimum: 0, maximum: 100 },
          description: 'A list of allowable gap lengths, in msec, up to 30 items long.',
        },
        TimeLead: {
          type: 'number',
          nullable: true,
          default: 1000,
          minimum: 0,
          maximum: 2000,
          description: 'Leading delay before gap can be inserted, in msec.',
        },
        TimeTrail: {
          type: 'number',
          nullable: true,
          default: 1000,
          minimum: 0,
          maximum: 2000,
          description: 'Trailing delay needed after gap, in msec.',
        },
        TimeWindow: {
          type: 'number',
          nullable: true,
          default: 850,
          minimum: 0,
          maximum: 2000,
          description: 'Length of window during which response can be accepted, in msec.',
        },
        TimeNoResp: {
          type: 'number',
          nullable: true,
          default: 100,
          minimum: 0,
          maximum: 200,
          description: 'Delay between beginning of gap and beginning of response window, in msec.',
        },
        TimePause: {
          type: 'number',
          nullable: true,
          default: 1000,
          minimum: 0,
          maximum: 5000,
          description: 'Elapsed time between presentations, in msec.',
        },
        GapLengthStartIndex: {
          type: 'number',
          nullable: true,
          default: 8,
          minimum: 0,
          maximum: 29,
          description: 'Index into AllowableGapLengths for initial gap length value.',
        },
        NReversalsCalc: {
          type: 'number',
          nullable: true,
          default: 8,
          minimum: 1,
          maximum: 10,
          description: 'Number of reversals to use in computation of threshold.',
        },
        NReversals: { type: 'number', nullable: true, default: 10, minimum: 1, maximum: 20, description: 'Number of reversals before test ends.' },
        NLowestReversals: {
          type: 'number',
          nullable: true,
          default: 3,
          minimum: 0,
          maximum: 10,
          description: 'Number of lowest pairwise reversal averages to track for second threshold computation.',
        },
        NPresMax: {
          type: 'number',
          nullable: true,
          default: 120,
          minimum: 1,
          maximum: 200,
          description: 'Maximum number of presentations to use before aborting the exam.',
        },
        NHits: {
          type: 'number',
          nullable: true,
          default: 2,
          minimum: 1,
          maximum: 3,
          description: 'Consecutive hits necessary before reducing gap length.',
        },
        NMiss: {
          type: 'number',
          nullable: true,
          default: 2,
          minimum: 1,
          maximum: 3,
          description: 'Consecutive misses necessary before increasing gap length.',
        },
        NPresCheck: {
          type: 'number',
          nullable: true,
          default: 5,
          minimum: 1,
          maximum: 8,
          description: 'Consecutive presentations with same gap length allowed.',
        },
        MaxFreq: {
          type: 'number',
          nullable: true,
          default: 16000,
          minimum: 4000,
          maximum: 16000,
          description: 'Maximum frequency used to generate the white noise, in Hz.',
        },
        UseSoftwareButton: {
          type: 'boolean',
          nullable: true,
          default: false,
          description: 'Uses a software submission instead of the mechanical button.',
        },
        SendFullResults: {
          type: 'number',
          nullable: true,
          enum: [0, 1, 2],
          default: 0,
          description: 'When to transmit thresholds and array results. 0=Always, 1=Sometimes, 2=Never.',
        },
        SemiAutomaticMode: {
          type: 'boolean',
          nullable: true,
          default: false,
          description: 'If true, pause after each pulse train to wait for a response.',
        },
      },
      required: [],
    },
  },
  required: ['type'],
};
