import { JSONSchemaType } from 'ajv';
import { ThreeDigitResponseAreaInterface } from '../../app/views/response-area/response-areas/three-digit/three-digit.interface';

export const threeDigitSchema: JSONSchemaType<ThreeDigitResponseAreaInterface> = {
  type: 'object',
  description: 'CHA - Three Digit Test',
  properties: {
    type: { type: 'string', enum: ['threeDigitResponseArea'] },
    enableSkip: { type: 'boolean', nullable: true, default: false },
    responseRequired: { type: 'boolean', nullable: true, default: false },
    tabsintId: { type: 'string', nullable: true, default: '1' },
    autoSubmit: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: 'Go straight to next page once this page is complete',
    },
    autoSubmitPresentation: {
      type: 'boolean',
      nullable: true,
      default: true,
      description: 'Go straight to next presentation once this presentation is complete',
    },
    autoBegin: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: "Go straight into exam, without having to press the 'Begin' button",
    },
    keypadDelay: {
      type: 'number',
      nullable: true,
      default: 10,
      description: 'Number of milliseconds to wait before activating the keypad',
    },
    feedback: {
      type: 'boolean',
      nullable: true,
      default: true,
      description: 'Shows the user which digits were correct after each set of digits is entered',
    },
    feedbackDelay: {
      type: 'number',
      nullable: true,
      default: 1000,
      description:
        'Number of milliseconds to show the digits after the presentation before clearing the keypad. This field can be used even when `feedback` is set to `false`',
    },
    examInstructions: {
      type: 'string',
      nullable: true,
      description: 'Replaces the top-level instruction text on the CHA exam pages (each page after starting page)',
    },
    measureBackground: {
      type: 'string',
      nullable: true,
      enum: ['ThirdOctaveBands'],
      description: 'Select a method to measure background noise after an exam.',
    },
    exportToCSV: {
      type: 'boolean',
      nullable: true,
      default: false,
      description: 'Whether result should be exported to CSV upon submitting exam results.',
    },
    examProperties: {
      type: 'object',
      nullable: true,
      properties: {
        nPresentations: {
          type: 'number',
          nullable: true,
          default: 50,
          minimum: 1,
          maximum: 100,
          description: 'Number of presentations',
        },
        warmupN: {
          type: 'number',
          nullable: true,
          default: 10,
          minimum: 0,
          maximum: 100,
          description: 'Number of presentations during the warmup period',
        },
        targetType: {
          type: 'string',
          nullable: true,
          enum: ['filtered', 'timeCompressed', 'H3CamFiltered', 'TFS', 'Swahili', 'MANDARIN', 'PORTUGUE', 'French'],
          default: 'filtered',
          description: 'Type of target material',
        },
        maskerType: {
          type: 'string',
          nullable: true,
          enum: ['schroeder', '2babble'],
          default: 'schroeder',
          description: 'Type of Masker Material',
        },
        warmupMasker: {
          type: 'string',
          nullable: true,
          enum: ['none', 'negativePhase', 'positivePhase', '2babble'],
          default: 'positivePhase',
          description: 'Type of Masker Material used during the warmup period.',
        },
        initialSNR: {
          type: 'number',
          nullable: true,
          default: 0,
          minimum: -25,
          maximum: 25,
          description: 'Signal to Noise Ratio of the first presentation',
        },
        fixedLevel: {
          type: 'number',
          nullable: true,
          default: 75,
          minimum: 0,
          maximum: 100,
          description: 'Level of either the target or the masker, whichever is fixed, in dB SPL',
        },
        fixedMaterial: {
          type: 'string',
          nullable: true,
          enum: ['target', 'masker'],
          default: 'target',
          description: 'Defines whether the "target" or the "masker" is presented at fixed level (the other is adjusted to get the desired SNR)',
        },
        correctStep: {
          type: 'number',
          nullable: true,
          default: -0.5,
          minimum: -25,
          maximum: 25,
          description: 'SNR step size for each correct digit in the previous response',
        },
        incorrectStep: {
          type: 'number',
          nullable: true,
          default: 2,
          minimum: -25,
          maximum: 25,
          description: 'SNR step size for each incorrect digit in the previous response',
        },
        warmupCorrectStep: {
          type: 'number',
          nullable: true,
          default: -0.5,
          minimum: -25,
          maximum: 25,
          description: 'SNR step size for each correct digit in the previous response during the warmup period',
        },
        warmupIncorrectStep: {
          type: 'number',
          nullable: true,
          default: 2,
          minimum: -25,
          maximum: 25,
          description: 'SNR step size for each incorrect digit in the previous response during the warmup period',
        },
        ear: {
          type: 'string',
          nullable: true,
          enum: ['left', 'right', 'both'],
          default: 'both',
          description: 'Which ear to use for the output',
        },
      },
      required: [],
    },
  },
  required: ['type'],
};
