# This workflow covers automatic releases in the GitHub mirror.
# It assumes that the GitLab pipeline has pushed the related zip file to the GitLab package registry.
name: Release Workflow

on:
  push:
    tags:
      - "v*" # Versioned tags (ex. v1.0.0)

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Android release for ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Download Zip from GitLab
        run: |
          curl --fail -L \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            "${{ secrets.GITLAB_API_V4_URL }}/projects/${{ secrets.GITLAB_PROJECT_ID }}/packages/generic/android/${{ github.ref_name }}/app-release.zip" \
            -o app-release.zip
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release.zip
          asset_name: app-release.zip
          asset_content_type: application/zip
